### ISSUE TITLE
I have no clue what this would be called end lag? proxy lag? idfk

### ISSUE THREAD

**Issue by SkitSkit** [FrozenOrb/HCTeams-Issues#13]
I have no clue why but every time I go to the end on HCTeams i instantly go to a 1 bar and always time-out, this usually happens if im moving in the end. I found out recently that if I am near the exit i go back to what i normally get which is a 4 bar. Like i dont get it, since this only happens in the end and im connection is perfect/stable in every other 'dimension'.  Like i know it not my pc its pretty good soo maybe its server sided?

Just want to add: could show u if u want.

**Comment by jhalt** [comment]
This sounds like a connection-related issue and I have not heard of any other reports related to this. Sorry :(
