### ISSUE TITLE
Regeneration I not working with Miner class.

### ISSUE THREAD

**Issue by ShortsPvP** [FrozenOrb/HCTeams-Issues#15]
Once you unlock the regeneration I feature in the iron Miner class on HCTeams, the regeneration does not indeed give the healing effect. It makes the health bar animation when you have regeneration but doesn't actually regenerate your health. If you need any more information or need me to try to duplicate it again don't hesisitate to contact me back.

You can see in this video I uploaded here: https://www.youtube.com/watch?v=EHk9pBJzXBM

Thanks,
Shorts

**Comment by TheRealGuru** [comment]
Miner is not intended a PvP kit anyway. A nerf to resistance II will be coming shortly however I have put through a change that will fix regeneration. Note that this isn't live and still needs deployment.
