### ISSUE TITLE
Deny claiming wand on kitmap

### ISSUE THREAD

**Issue by Alexandeh** [FrozenOrb/HCTeams-Issues#18]
Players can type "**/f claim**" to receive a claiming wand on kitmap. They are shown an error message but are **still** given the actual wand. Claiming functions are non-existent, however, when a player interacts with the wand it becomes a regular usable hoe.

GIF demonstration: https://gyazo.com/65855e31df2579eb4c09cfbcb9fcc70a
Video demonstration: https://youtu.be/Flt8ejy0maQ _Excuse music, Spotify is life_

**Comment by TheRealGuru** [comment]
Added a fix, not pending QA :).

**Comment by jhalt** [comment]
Should be resolved in https://github.com/FrozenOrb/HCTeams/commit/8c991087694d186e8161ea2dd10bb621cc3c44ef.
