### ISSUE TITLE
Kit map ban table not synced

### ISSUE THREAD

**Issue by Aspecting** [FrozenOrb/HCTeams-Issues#20]
I was unblacklisted a few days ago, and upon joining the kit map, I receive the same blacklist message.

**Comment by jhalt** [comment]
This is due to APIv3 being run on Kit Map. This is intentional. These bans will eventually be merged together once APIv3 is determined to be stable for production.

**Comment by BizarreAlex** [comment]
@jhalt Is that why my rank is visible on every server besides kitmap or is that another issue on its own?

**Comment by colinmcdonald22** [comment]
@BizarreAlex correct

**Comment by BizarreAlex** [comment]
@colinmcdonald22 Ah, makes sense. Thank you for the clarification.
