### ISSUE TITLE
Bard/Archer effect items not being taken away

### ISSUE THREAD

**Issue by Strafin** [FrozenOrb/HCTeams-Issues#25]
Bard: When you use the wither effect (spider eyes) if you only have 1 spider eye in your hand it never takes the item away.

Archer: When you use the jump boost effect in archer you never lose a feather (feature?)

**Comment by TheRealGuru** [comment]
Blitz said this is indeed unintentional so I'll get this done shortly.

**Comment by TheRealGuru** [comment]
Fixed - Pending QA.

**Comment by jhalt** [comment]
This IS in fact intentional, Blitz was wrong. This needs to be reverted.
