### ISSUE TITLE
Further prevent combat-tagged players from entering safezones

### ISSUE THREAD

**Issue by BizarreAlex** [FrozenOrb/HCTeams-Issues#27]
A player can be in spawn whilst combat-tagged.

I accomplished this by sneaking on the border of spawn (whilst in warzone) and getting hit towards spawn. Not necessarily a _game breaking_ bug as it has been impossible for me to reproduce it without positioning myself in a certain way (which takes time). 

This could be fixed by introducing a countermeasure that would teleport players who are both tagged and in a safezone outside (using an algorithm similar to "_/f stuck_")**.

Video demonstration: https://youtu.be/I6xcnwTFLOU

**EDIT**: I noticed after attempting to reproduce the bug again that there is already an existing countermeasure to prevent players from entering spawn (besides the glass wall). You can actually see it in the GIF below -- I am sent a bold red message stating that I can't enter spawn and am teleported back.

**EDIT**: After carefully watching the video, I noticed that when I was hit the last claim-update message was that I had entered Spawn. This could be due to the claim-update messages being sent after a delay, I've decided to comment about it anyways.

![Image](https://i.gyazo.com/35c4c66797f43138b22438be0025aaf0.gif)

** _This is based on the belief that there is currently no code providing the kind of countermeasures mentioned. If that is not the case, then the problem would be due to the code itself -- not the absence of code._ **See first edit**

**Comment by TheRealGuru** [comment]
Going to class this as a nofix. I don't believe this is an issue except, and more the result of latency / asynchronous code. Thanks for the report.

**Comment by BizarreAlex** [comment]
Not sure if the two are related, but there are times where I will respawn and still be tagged whilst in spawn.
