### ISSUE TITLE
[Enhancement] Coordinates

### ISSUE THREAD

**Issue by defcn** [FrozenOrb/HCTeams-Issues#28]
Just a quick enhancement, I thought this might help the community even tho i'm banned (Not ban appeal.) I'm working on my own core so this is why i wrote it, this lets players type /c and it types there coordinates in chat this makes their teammates able to help them and lets them post coords fast
GIF: 
[Gyazo](https://gyazo.com/1443d0bb0a0be6cf4e77e207845044bf)
Code:
`
	
	public boolean onCommand(CommandSender s,  Command c, String l, String[] args) {
		
		Player p = (Player) s;
		
		int x = p.getLocation().getBlockX();
		int y = p.getLocation().getBlockY();
		int z = p.getLocation().getBlockZ();
		
		String xs = Integer.toString(x);
		String ys = Integer.toString(y);
		String zs = Integer.toString(z);
		
		String coordinates = ChatColor.RESET + "X: " + xs + " " + "Y: " + ys + " " + "Z: " + zs;
		
		if(c.getName().equalsIgnoreCase("c")) {
			
			p.chat(coordinates);
			
		}
		
		return true;
		
	}

}`

Sorry if the formatting is messed up :\ just github.

**Comment by defcn** [comment]
This is just to help players!

**Comment by ItsMonkeyyy** [comment]
I don't see how this would be useful at all. Sorry if that sounds harsh but it's the truth.

**Comment by defcn** [comment]
lets say your getting ganked, you need to post your coords u type /c and posts your coords for your faction . @ItsMonkeyyy

**Comment by ItsMonkeyyy** [comment]
@defcn It still doesn't seem like something that would be needed

**Comment by defcn** [comment]
@ItsMonkeyyy Idk.

**Comment by TheRealGuru** [comment]
`public boolean onCommand(CommandSender s,  Command c, String l, String[] args) {

    Player p = (Player) s;

    String coordinates = ChatColor.RESET + "X: " + x + " " + "Y: " + y + " " + "Z: " + z;

    if(c.getName().equalsIgnoreCase("c")) {

        p.chat(coordinates);

    }

    return true;

}`
You might want to use it like that, casting it to a string is completely pointless and a minor waste of efficiency, either way we have no need for this, thanks anyway.

**Comment by defcn** [comment]
@TheRealGuru Mb it was late so i didn't relize
