### ISSUE TITLE
Minecarts are being abused to teleport vertically.

### ISSUE THREAD

**Issue by jhalt** [FrozenOrb/HCTeams-Issues#5]
Requesting further clarification and reproduction information/screenshots/videos from @J3wellZ.

**Comment by J3wellZ** [comment]
Screenshot:
http://prntscr.com/bfjvdr

GIF - How it works
https://gyazo.com/816a546ad5472885189f2e30255f12ae

**Comment by jhalt** [comment]
The community has asked us not to fix this. As of present, we will stick with the community's request:
https://www.reddit.com/r/hcteams/comments/4nvg1h/keep_the_minecart_teleportation_glitch/
