### ISSUE TITLE
Highroller Prefix Disappearing on Reboots

### ISSUE THREAD

**Issue by Looked** [FrozenOrb/HCTeams-Issues#9]
Every time the server reboots I lose my highroller prefix in front of my name but keep my lives and have to get the prefix added back manually. I think it is being worked on just wanted to check on here. Thanks

**Comment by TheRealGuru** [comment]
Please check out issue #4 this issue is already in progress and is pending deployment to our servers. Thanks for your concern. Closing this ticket.
